### ISSUE TITLE
window focus issue

### ISSUE THREAD

**Issue by Owyn** [SerenTera/afk-notify#4]
when I have TERA minimized and have another game in fullscreen and a tera notifier notification pops-up - that pop-up takes the focus... and whenever I click my mouse - it minimizes my main non-tera game and focuses on windows notification from Tera notifier :-(

**Comment by SerenTera** [comment]
That is a windows behavior unfortunately, the notifications it sends is the same as any other windows notification. There is something u can try tho, try set the tera-notifier setting to 'balloon' instead of 'toast' to use the alternative popup, with the same style as winXP era. You set this in 'tera-notifier' and not this module.

**Comment by Owyn** [comment]
yea, balloons work great I think, and those are the ones I've been getting always by default in my windows 10 which I've been used since it was released in beta-test state... I've never seen these "toasts" up until I installed this module so I had no issues of this "windows behavior"
